### ISSUE TITLE
Method to list supported browsers?

### ISSUE THREAD

**Issue by foolip** [saucelabs/node-saucelabs#111]
I've search https://wiki.saucelabs.com/display/DOCS/The+Sauce+Labs+REST+API and these bindings, but can't find a way to enumerate all the browsers which are supported.

BrowserStack has https://www.browserstack.com/docs/automate/api-reference/selenium/browser#get-browser-list, I'm looking for something similar.

**Comment by christian-bromann** [comment]
Hey @foolip,

you can use the [`listPlatforms`](https://github.com/saucelabs/node-saucelabs/blob/main/docs/interface.md#example-7) command, e.g.:

```sh
$ sl listPlatforms webdriver
```
or
```
const api = new SauceLabs()
const platforms = await api.listPlatforms("webdriver")
```

Other platform options are `selenium-rc`, `appium` or `all`. We are working on improving the docs around all these API interfaces. Let me know if you have further questions.

**Comment by foolip** [comment]
Thanks @christian-bromann, I got that to work with your example, thanks!

I also found https://wiki.saucelabs.com/display/DOCS/Platform+Information+Methods for the underlying REST API.

I do have a follow-up question: given an entry from that long list of platforms, is there a reliable way of turning that into WebDriver capabilities for connecting to exactly that configuration? I'm not sure if I'm doing it right or if lax matching in some layer could lead to two browser versions being treated as the same. In particular I'm wondering about Safari 13 vs. 13.1, since both have the same `short_version`.

**Comment by christian-bromann** [comment]
Sure, let's say you have:

```json
   {
        "short_version": "13",
        "long_name": "Safari",
        "api_name": "safari",
        "long_version": "13.1.",
        "latest_stable_version": "",
        "automation_backend": "webdriver",
        "os": "Mac 10.15"
    }
```
If you would use WebdriverIO you could do:

```js
import { remote } from 'webdriverio'

const platform = { ... } // see above

;(async function () => {
    const browser = remote({
        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
        capabilities: {
            browserName: platform.api_name,
            platformName: platform.os,
            browserVersion: platform.long_version
        })
    })

    // ...
})().catch(console.error)
```

Would that make sense?

**Comment by foolip** [comment]
Thanks @christian-bromann, if passing along the values works that's great, and easier than I thought from trying to do something similar a few years ago. I'll give it another try :)
