### ISSUE TITLE
Feature: Add app uploads to this module

### ISSUE THREAD

**Issue by wswebcreation** [saucelabs/node-saucelabs#114]
I would be great if this module would also provide the ability to upload apps to the Sauce Labs EU/US/(APAC?) storage. This is an example script I now use

https://github.com/webdriverio/appium-boilerplate/blob/main/scripts/push_apps_to_sauce_storage.sh

**Comment by waggledans** [comment]
Sauce Labs-recommended way for the app storage access is via [saucectl upload](https://docs.saucelabs.com/dev/cli/saucectl/storage/upload/) command. For example:

```
saucectl storage upload ../apps/iOS-Simulator-NativeDemoApp-$VERSION.app.zip --description "My iOS app release"
```

Having said that, there is an open issue for adding app storage API to this module: https://github.com/saucelabs/node-saucelabs/issues/108

it will cover all storage interactions, including app upload.
