### ISSUE TITLE
Update build URL returned by listBuilds command

### ISSUE THREAD

**Issue by poonamsl** [saucelabs/node-saucelabs#121]
*Short summary of what the user sees:*
The 'listBuilds' command is returning the old build URL.
https://app.saucelabs.com/builds/<BUILD_ID>

*Assistance Requested*
Please update it to return the new build URL 
https://app.saucelabs.com/builds/vdc-v2/<BUILD_ID>

**Comment by boneskull** [comment]
@waggledans I'm not sure if this is still an issue, but from what I can tell, this module returns the result of the API call verbatim.  It looks like the endpoint contains `getBuildsV2`.  Does this module need to use a different endpoint, or is it an issue on SL's side?

**Comment by boneskull** [comment]
Maybe this is a question for VDC

**Comment by waggledans** [comment]
not sure who owns this endpoint.
