### ISSUE TITLE
bin-wrapper is problematic

### ISSUE THREAD

**Issue by boneskull** [saucelabs/node-saucelabs#134]
[bin-wrapper](https://github.com/kevva/bin-wrapper) is seemingly unmaintained.  There's a [ReDoS vuln](https://github.com/advisories/GHSA-44c6-4v22-4mhx) in a deep transitive dependency (`semver-regex`).  Sending a PR to address this problem (to `bin-wrapper`) is probably futile.  Here are our options:

1. Remove `bin-wrapper` and replace it with something else.  That something else might mean "DIY".
2. Look for a fork of `bin-wrapper` which has already addressed the vuln, and use that instead (probably unlikely).
3. Fork `bin-wrapper`, update the `bin-version-check` dependency to v5 or newer, and re-publish (under e.g., `@saucelabs/bin-wrapper`). _However_, `bin-version-check@5` is an ESM-only module, which will probably be painful to deal with.

Thoughts?  We are getting complaints.

**Comment by boneskull** [comment]
Further:

- `bin-wrapper` uses an old version of `bin-version-check`
- `bin-version-check` attempts to parse the version displayed by `<executable> --version` using semver
- but it does not appear we actually need to parse the version; all we need to do is grep for the required version as returned by `sc`.  

`bin-version` is pretty straightforward, and we can simplify it if rolling our own, which I don't believe is unreasonable.

**Comment by wswebcreation** [comment]
I can take a look at it tomorrow @boneskull

**Comment by boneskull** [comment]
@wswebcreation Any thoughts?  If you don't have the cycles, I am happy to work on this.
