### ISSUE TITLE
query-string might need to be a dependency instead of a devDependency

### ISSUE THREAD

**Issue by josueuitzil** [saucelabs/node-saucelabs#143]
Hi devs, 
I noticed that the stringify function of the query-string library is imported and used in the index file: https://github.com/saucelabs/node-saucelabs/blob/7e9c5fba5457ae144f748b2eb70acd25c1661cef/src/index.js#L8

Which results in it being also required in the build:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/61981074/172892934-6b66b43a-b905-47b4-86ad-c442910181d1.png">

Since that library is set only as a devDependency in the package.json, when node-saucelabs is installed in a project, the query-string library is taken from a nested dependency:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/61981074/172893428-be1fd9e6-d8c9-49a4-9cd2-45b76ee71a94.png">

I think this could be problematic if the version of normalize-url gets updated in the future (query-string stopped being required in v3 of normalize-url) or if a project uses npm resolutions.
This could also cause unexpected bugs, since development of the package is done using version ^7.0.1 of query-string, while once installed it will use version 5.

I think this could be avoided by having the library as a dependency instead of just a devDependency. What do you think?

**Comment by borayuksel1903** [comment]
This is causing issues on our end as well by not being able to find query-string dependency. It works if `normalize-url` has a lower version in the repo, however, if there is a conflicting higher version that `npm` resolves to, `query-string` won't get installed.

Could we get this issue addressed please? Thank you!

**Comment by richallanb** [comment]
echoing sentiment from @borayuksel1903,
Any chance this is going to get fixed? I see a PR open for this problem from almost a year ago.
This seems like a really simple and safe thing to address.
