### ISSUE TITLE
npm audit surfaces 'got' dependency vulnerability

### ISSUE THREAD

**Issue by alexrivadeneira** [saucelabs/node-saucelabs#150]
Hello,

My organization's project uses saucelabs and running `npm audit` surfaced a vulnerability that's a dependency of `saucelabs` (using the latest version):

```
# npm audit report

got  <11.8.5
Severity: moderate
Got allows a redirect to a UNIX socket - https://github.com/advisories/GHSA-pfrx-2q88-qq97
fix available via `npm audit fix`
node_modules/download/node_modules/got
  download  >=4.0.0
  Depends on vulnerable versions of got
  node_modules/download
    saucelabs  >=7.1.3
    Depends on vulnerable versions of download
    node_modules/saucelabs
```
(running `npm audit fix` or `npm audit --force fix` does not do anything)

Do you have any more information about this issue?

**Comment by mat-sharp** [comment]
Also seeing this issue while evaluating this product.

**Comment by diemol** [comment]
Should be closed by  https://github.com/saucelabs/node-saucelabs/pull/144 and a new package was just released https://github.com/saucelabs/node-saucelabs/releases/tag/7.2.1
