### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by Morte83** [saucelabs/node-saucelabs#207]
CJS compatibility has been lost starting from version 7.2.4 since “query-string” dependency was bumped to version 8.0.1 which has breaking change, it became pure ESM. Is there any plans to return CommonJS compatibility?

**Comment by diemol** [comment]
While fixing #157, I bumped a few dependencies, which was an oversight. I missed in their release notes the fact they moved to ESM. 

I replaced the original `download` dependency with https://github.com/XhmikosR/download, which now I see it is also ESM. 

I probably need to revert this and find an alternative.

**Comment by diemol** [comment]
The idea would be to do one last release supporting CommonJS without vulnerabilities and, after that, move to ESM.

**Comment by Morte83** [comment]
It would be very nice to have backward compatibility to CommonJS in future versions.

**Comment by gromanas** [comment]
Hello!!! Any news on this? there is a commit [here](https://github.com/saucelabs/node-saucelabs/commit/a7814104cc324035901b9ade7d89c34182783175#commitcomment-127284025). If any help is needed please let me know so I can help on this.
