### ISSUE TITLE
Readiness check of Sauce Connect Proxy 5 does not work

### ISSUE THREAD

**Issue by naruaway** [saucelabs/node-saucelabs#242]
Note that this issue is not specific to node-saucelabs but I am posting here since it should be also relevant for node-saucelabs if Sauce Labs wants to support Sauce Connect Proxy 5 in node-saucelabs. Also simply I want to use GitHub to report issues since I can just use markdown.

Note that in this document, I'll use "v4" and "v5" to indicate Sauce Connect Proxy 4 and Sauce Connect Proxy 5 respectively.

For v4, typically driver code waits for "Sauce Connect is up, you may start your tests" message from stdout of "sc" binary ([example in node-saucelabs](https://github.com/saucelabs/node-saucelabs/blob/8c507b828456daaacc3f51b2ef4bbfbca5bd4615/src/index.js#L345-L350)). Alternatively, we can also use [Sauce Connext Proxy API Server](https://docs.saucelabs.com/secure-connections/sauce-connect-5/operation/api-server/), specifically `/readyz` endpoint. Both of these just work fine for v4.

## Problem

For v5, neither waiting for "Sauce Connect is up, you may start your tests" nor using `/readyz` endpoint does not work.
Even after either of these readiness check completes, actually the tunnel is not ready and creating a new session via `https://ondemand.us-west-1.saucelabs.com/wd/hub/session` fails with "Misconfigured -- No active tunnel found for provided identifier" error.

Note that I figured out a workaround. We can additionally call [Sauce Connect API Endpoints](https://docs.saucelabs.com/dev/api/connect/), specifically `/rest/v1/{username}/tunnels/{tunnel_id}` to periodically check `is_ready` flag.
However, this workaround has the following drawbacks:

- Additional code (Sauce Connect API Endpoints calls) is needed compared with v4
- Since we need to periodically call `/rest/v1/{username}/tunnels/{tunnel_id}` to checck `is_ready`, it adds additional burden for both server and client, also Sauce Connect start up will be less efficient.
- Simply, the behavior is "wrong" since "Sauce Connect is up, you may start your tests" is basically telling a lie and `/readyz` endpoint is not working as explained.

## Desired solution

I would like v5 behave exactly the same as v4 in terms of readiness check, which means the following:

- Creating a new WebDriver session immediately after observing "Sauce Connect is up, you may start your tests" should not fail
- Creating a new WebDriver session immediately after `/readyz` returns 200 should not fail

Note that for our specific use case, so far I am thinking to rely on "Sauce Connect is up, you may start your tests" rather than `/readyz` since it's simpler and this is the way [how node-saucelabs is checking the readiness of v4](https://github.com/saucelabs/node-saucelabs/blob/8c507b828456daaacc3f51b2ef4bbfbca5bd4615/src/index.js#L345-L350).

## Minimum reproducible example for macOS (the same issue also exists for Linux)

Please create a fresh temporary directory and execute the following shell script to download v4 and v5.

```
#!/bin/bash
set -euo pipefail

## Download Sauce Connect Proxy binary (sc) v4
rm -rf scbin/4
mkdir -p scbin/4
curl -L https://saucelabs.com/downloads/sc-4.9.1-osx.zip > scbin/4/sc.zip
(cd scbin/4 && unzip -q sc.zip)
mv scbin/4/*/bin/sc scbin/4

## Download Sauce Connect Proxy binary (sc) v5
rm -rf scbin/5
mkdir -p scbin/5
curl -L https://saucelabs.com/downloads/sauce-connect/5.0.1/sauce-connect-5.0.1_darwin.all.zip > scbin/5/sc.zip
(cd scbin/5 && unzip -q sc.zip)
```

Then save the following file as `test-sc-readiness-behavior.mjs` and execute it via Node.js v20 with a single argument to specify "4" or "5" like `node test-sc-readiness-behavior.mjs 4` or `node test-sc-readiness-behavior.mjs 5`.

```javascript
import { spawn } from "node:child_process";
import { webcrypto as crypto } from "node:crypto";
import * as path from "node:path";

const tunnelName = "test-sc-readiness-behavior-" + crypto.randomUUID();
const scVersion = process.argv[2];
if (scVersion !== "4" && scVersion !== "5") {
  throw new Error(`scVersion must be either 4 or 5`);
}

const { SAUCE_USERNAME, SAUCE_ACCESS_KEY } = process.env;
if (!SAUCE_USERNAME || !SAUCE_ACCESS_KEY)
  throw new Error("Please supply SAUCE_USERNAME and SAUCE_ACCESS_KEY envvars");

const scBin = spawn(
  path.resolve("./scbin", scVersion, "sc"),
  scVersion === "4"
    ? ["--tunnel-name", tunnelName, "--region", "us-west"]
    : [
        "run",
        "--tunnel-name",
        tunnelName,
        "--region",
        "us-west",
        "--log-level",
        "info",
      ],
  { stdio: ["inherit", "pipe", "inherit"] },
);

scBin.stdout.setEncoding("utf8");

console.log(
  'waiting for "Sauce Connect is up, you may start your tests" message from sc binary',
);
await new Promise((resolve) => {
  scBin.stdout.on("data", (data) => {
    console.log("[stdout of sc] " + data);
    if (data.includes("Sauce Connect is up, you may start your tests")) {
      resolve();
    }
  });
});
console.log(
  '"Sauce Connect is up, you may start your tests" message received from sc binary',
);

const webdriverUrl = "https://ondemand.us-west-1.saucelabs.com/wd/hub/session";

const res = await fetch(webdriverUrl, {
  method: "POST",
  headers: {
    authorization: "Basic " + btoa(`${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY}`),
    "content-type": "application/json",
  },
  body: JSON.stringify({
    capabilities: {
      alwaysMatch: {
        browserName: "safari",
        platformName: "ios",
        "appium:deviceName": "iPhone Instant Simulator",
        "appium:platformVersion": "current_major",
        "appium:automationName": "XCUITest",
        "sauce:options": {
          tunnelName,
        },
      },
    },
  }),
});
console.log(`${webdriverUrl} returned HTTP ${res.status}`);
console.log(await res.text());
scBin.kill("SIGKILL");
```

### The output of the minimum reproducible example in my environment

The last few lines of `node test-sc-readiness-behavior.mjs 4`:

```
"Sauce Connect is up, you may start your tests" message received from sc binary
https://ondemand.us-west-1.saucelabs.com/wd/hub/session returned HTTP 200
{"value": {"sessionId": "f324e847866b4ed78b3dc4342cf62faa", "webdriver.remote.sessionid": "f324e847866b4ed78b3dc4342cf62faa", "hasMetadata": true, "capabilities": {"deviceName": "iPhone 14", "takesScreenshot": true, "orientation": "PORTRAIT", "networkConnectionEnabled": false, "selenium:webdriver.remote.quietExceptions": false, "bootstrapPath": "/Volumes/Sauce/wda/wda-v2.0.0-xcode13.0/WebDriverAgent", "newCommandTimeout": 0, "preventWDAAttachments": true, "sauce:options": {}, "derivedDataPath": "/Volumes/Sauce/wda/wda-v2.0.0-xcode13.0/WebDriverAgent/DerivedData/WebdriverAgent", "locationContextEnabled": false, "platform": "MAC", "maxTypingFrequency": 8, "platformName": "ios", "showIOSLog": false, "javascriptEnabled": true, "automationName": "XCUITest", "databaseEnabled": false, "noReset": true, "usePrebuiltWDA": true, "browserName": "safari", "proxy": {"proxyAutoconfigUrl": "https://localhost:19876/pac.js", "proxyType": "pac"}, "platformVersion": "16.2", "webStorageEnabled": false, "eventTimings": true, "keepKeyChains": true, "launchTimeout": 240000, "udid": "F3CDBC72-83CC-4CC0-A945-0F9DB4526CC1", "backendRetries": 4}}}
```
The last few lines of `node test-sc-readiness-behavior.mjs 5`:

```
"Sauce Connect is up, you may start your tests" message received from sc binary

https://ondemand.us-west-1.saucelabs.com/wd/hub/session returned HTTP 400
Sauce could not start your job. For more information on what happened, please visit https://app.saucelabs.com/tests/0f2bdee3ff5e4c5495e747b7c3fa492f
```

This indicates that the readiness check based on "Sauce Connect is up, you may start your tests" message only works for v4, not v5.

**Comment by alexh-sauce** [comment]
Thanks for this detailed report. We're looking into it.

**Comment by naruaway** [comment]
Thanks, I realized that Sauce Labs (secretly?) released Sauce Connect Proxy binary v5.1.0.
I replaced the URL in the above script with `https://saucelabs.com/downloads/sauce-connect/5.1.0/sauce-connect-5.1.0_darwin.all.zip` and confirmed now it works like v4 as expected 🎉 

@alexh-sauce I guess you will update the following soonish?

- https://api.us-west-1.saucelabs.com/rest/v1/public/tunnels/info/versions?client_version=5 still returns 5.0.1
- https://docs.saucelabs.com/secure-connections/sauce-connect-5/installation/ still shows 5.0.1

**Comment by alexh-sauce** [comment]
Yes, 5.1.0 is officially released now. Thanks for the report!

**Comment by naruaway** [comment]
Note: `/readyz` is still broken for the latest v5 (I checked v5.2.0 on macOS) so we need to rely on "Sauce Connect is up, you may start your tests" message from stdout. This is fine as long as `sc` does not change the log message. Also also listening for stdout log is somehow more efficient than polling for /readyz at some periodic schedule

**Comment by naruaway** [comment]
FYI: I confirmed that with v5.3.0, `/readyz` is finally working 🎉
