### ISSUE TITLE
Add more single job methods

### ISSUE THREAD

**Issue by kidmillions** [saucelabs/node-saucelabs#32]
I'd love to add [getJobAssetFiles](https://wiki.saucelabs.com/display/DOCS/Job+Methods#JobMethods-GetJobAssetFileshttps://wiki.saucelabs.com/display/DOCS/Job+Methods#JobMethods-GetJobAssetFiles) to the prototype. This and a few other job methods available in the api are not yet in this wrapper: 

```
SauceLabs.prototype.getJobAssetFiles = function (id, filename, callback) {
    this.send({
        method: 'GET',
        path: ':username/jobs/:id/assets/:filename',
        args: { id: id, filename: filename },
    }, callback);
};
```

**Comment by halkeye** [comment]
@kidmillions have you tried creating a pull request for this?

**Comment by wswebcreation** [comment]
All API methods for the Sauce Labs Desktop browsers and the Real Device clouds are now provided. More info can be found [here](https://github.com/saucelabs/node-saucelabs/blob/master/docs/interface.md).

If there are still any questions feel free to submit an issue
