### ISSUE TITLE
Add TypeScript Definitions

### ISSUE THREAD

**Issue by simonua** [saucelabs/node-saucelabs#42]
TypeScript-based consumers of node-saucelabs could use TypeScript definitions. Currently, an instance of node-saucelabs can only be typed as the general `any`. 

Some projects include their own `d.ts` files, but that's typically done if the code is TypeScript-based. In the case of node-saucelabs, adding a definition to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo would be more appropriate, which would allow for `@types/node-saucelabs` to be installed from npm.

**Comment by christian-bromann** [comment]
This should be much easier now to implement thanks to the swagger definitions this API is based on. Any contribution would be highly appreciated.

**Comment by simonua** [comment]
@christian-bromann, could you tell me where the swagger definitions are referenced, please?

**Comment by wswebcreation** [comment]
@simonua 

You can find them here https://github.com/saucelabs/node-saucelabs/tree/master/apis

**Comment by simonua** [comment]
Awesome, @wswebcreation! I'll see if I can take a look in the next week or two but can't promise I'll be able to get to it soon.

**Comment by zewa666** [comment]
@simonua a basic first shot is now implemented. Granted a few endpoints could use better typings instead of a naked `object`. So if you're about to test this I'm happy about any feedback to see what can be further improved

**Comment by christian-bromann** [comment]
@zewa666 thanks for all the work 👏
