### ISSUE TITLE
Embed Sauce Connect support

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/node-saucelabs#53]
There is no reason to have a separate package to use Sauce Connect. We should embed this functionality into this package. It should ensure to always use the latest SC version and only download it when needed and not available.

**Comment by valishah** [comment]
Hi @christian-bromann: Do you mean getting proxy tunnel creation to the package?

**Comment by christian-bromann** [comment]
Yes, like embedding the `sauce-connect-launcher` package into this. However this package seems to still be maintained so this is not that urgent.

**Comment by valishah** [comment]
Okay. Thanks for the response. 👍

**Comment by christian-bromann** [comment]
This has been implemented in [`v4.5.1`](https://github.com/saucelabs/node-saucelabs/releases/tag/v4.1.0).
