### ISSUE TITLE
As npm package sample is wrong

### ISSUE THREAD

**Issue by zewa666** [saucelabs/node-saucelabs#63]
Hey there,

looking at the sample provided with the latest update (after taking over the package) this clearly can't build. Where is that `user` coming from? Besides that the SauceLabs constructor expects a `options` object specifying the `user` and `key` aka accesskey as minimum.

What I wonder is that now most APIs do require the username. Why isn't that already forwarded from the provided options config?

**Comment by christian-bromann** [comment]
I think this is just not properly documented. I you create you create an instance like this:

```js
const myAccount = new SauceLabs()
```

it gets username and password from the environment (`SAUCE_USERNAME` and `SAUCE_ACCESS_KEY`). You can also pass in an option object:

```js
const myAccount = new SauceLabs({ user: 'foo', key: 'bar' })
```

**Comment by zewa666** [comment]
thats true, but if neither of the ENV is set you end up with an error of something along the lines "slice of undefined bla bla bla ..." which most likely points to this [section here](https://github.com/saucelabs/node-saucelabs/blob/master/src/index.js#L120). So proper error could be thrown instead to tell the user to either provide the options or define the ENV. Routes themselves do reject with `no auth mechanism defined`

Still, even when that is set, the shown sample pretty much can't run as the global `user` variable is not available.

```javascript
import SauceLabs from 'saucelabs';
// if imports are not supported by your Node.js version, import the package as follows:
// const SauceLabs = require('saucelabs').default;

(async () => {
    const myAccount = new SauceLabs();

    // get job details of last run job
    const job = await user.listJobs(   // <---------- where comes this user from? no window global defined
        process.env.SAUCE_USERNAME,
        { limit: 1, full: true }
    );
```

I'm not sure whether I miss something but I guess instead of user it's meant to be used as
```javascript
const job = await myAccount.listJobs()
```

Last but not least, with `listJobs` as an example, to cover my last question, you need to again pass on the username. Is there a reason for not picking up the provided username (options/env). Does that stem from saucelabs sub-accounts perhaps?

**Comment by christian-bromann** [comment]
> I'm not sure whether I miss something but I guess instead of user it's meant to be used as

Yes exactly. This is a bug in the documentation.

> Is there a reason for not picking up the provided username (options/env). Does that stem from saucelabs sub-accounts perhaps?

Yes, as you mention you could technically also fetch the details of a subaccount.
