### ISSUE TITLE
replacement for old getAllBrowsers (endpoint: info/browsers/all)

### ISSUE THREAD

**Issue by zewa666** [saucelabs/node-saucelabs#66]
with v1.x there was a route available to list all possible browser combinations.
We've made use of that for our endpoints builder.

The return was an array of simple browser descriptions:

```json
{
    "short_version": "27",
    "long_name": "Google Chrome",
    "api_name": "chrome",
    "long_version": "27.0.1453.110.",
    "latest_stable_version": "27",
    "automation_backend": "webdriver",
    "os": "Mac 10.13"
},
```

With the 2x branch I can't any longer find that path (info/browsers/all). Is there an alternative API endpoint now available for that?

Furthermore the new API should list that by region

**Comment by christian-bromann** [comment]
> Is there an alternative API endpoint now available for that?

No, what was the endpoint url?

**Comment by zewa666** [comment]
as mentioned `info/browsers/all`. Here's the old code from v1 https://github.com/saucelabs/node-saucelabs/blob/v1/lib/SauceLabs.js#L174

**Comment by christian-bromann** [comment]
This can be simply added by extending the swagger definition. The best way for that would be to improve our weak implemented swagger integration. However this could take some time so therefor I would recommend to make a PR to the generated one in this repository.

**Comment by zewa666** [comment]
Well typically swagger schemas are generated nowadays code-first from the backend so I'm not sure how to proceed here manually. Does this belong in `sauce.api`? But even if we scram those in how can we support the region setting? I guess the supported combinations can't be 1:1 for every region, especially when it comes to real devices. Talking about later is there any new API available to list those? Looking through the API description there is a `/v1/devices` endpoint which name is `api.getDescriptorsDeprecated()`. That does not sound too future-proof ;)

Looking at the [official configurator](https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/), which used to consume the API as far as I know, meanwhile it's using a bunch of pre-made json files. Yet even there I can't define the region setting. So I'm a bit lost on how to proceed here. If you could give me a few pointers I'd gladly try to come up with a PR

**Comment by zewa666** [comment]
I figured we can make use of `listPlatforms` and passing it either `all`, `webdriver` or `appium`. It doesn't fully reflect what was available with `getBrowsersAll` but should be a good start. In our case we anyway just need webdrivers and I'm not really sure what `getSeleniumBrowsers` was meant to do anyways. Guess it's for v1 Selenium-RC perhaps?

**Comment by christian-bromann** [comment]
Closing then. I will create an internal ticket to ensure we get this endpoint into the Swagger file. Thanks!
