### ISSUE TITLE
Support for real devices cloud 

### ISSUE THREAD

**Issue by valishah** [saucelabs/node-saucelabs#69]
As saucelabs started providing real devices testing support. Can we extend the API support of mobile browser testing also here? 

https://api.testobject.com/

**Comment by christian-bromann** [comment]
> Can we extend the API support of mobile browser testing also here?

It already does. Check the [docs](https://github.com/saucelabs/node-saucelabs/blob/master/docs/interface.md)

**Comment by valishah** [comment]
Thank you @christian-bromann: My bad. I missed it
