### ISSUE TITLE
Fetching list of active tunnels by user

### ISSUE THREAD

**Issue by valishah** [saucelabs/node-saucelabs#70]
Hello, 

While using the [Rest API](https://docs.saucelabs.com/dev/api/connect/) I could able to pull the active tunnels by `username`

Request: `rest/v1/USERNAME/tunnels`
Response: `['tunnel-id-1','tunnel-id-2']`

But while using the node module, I'm getting the information from all the users under the organization. Is it because of the user being admin? 

Request: `api.listAvailableTunnels(USERNAME)`
Response: 
```
{ "user-1": [], "user-2":[]}
```
Reference picture of fetching available tunnels
https://share.getcloudapp.com/BluJkZOJ

**Comment by christian-bromann** [comment]
> Is it because of the user being admin?

Yeah most likely. I can double check on that.

**Comment by valishah** [comment]
Sure. As we are expecting `SAUCE_USERNAME` from env  (or) 'user' during constructor initialization,  Asking for username to be mentioned while fetching `listOfAvailableTunnels` might not be needed I believe. 
Everything resides in a single process and object-level scope.

**Comment by christian-bromann** [comment]
> might not be needed I believe.

It is though since you can pull the data not only for your user but also for your sub-accounts.

**Comment by christian-bromann** [comment]
> If the user doesn't provide `username`, We can list all tunnels including sub-accounts.

This is more difficult. As you can see all API commands are generated based on the Swagger definition and all special behaviors need to be implemented separately.

**Comment by waggledans** [comment]
I believe updating API (a while ago) solved this problem. Specifying `username` with `all` returns a list of tunnel IDs for that user:

```
sl listTunnels my-org-user1
[
    "82758bd43ea44a10b776542107d5d929"
]
```

The `all` flag controls the response data to include all subaccounts:

```
sl listTunnels my-org-admin all
{
    "my-org-user1": [
        "82758bd43ea44a10b776542107d5d929"
    ],
   "my-org-user2": [
        "xxx"
    ]
}
```
