### ISSUE TITLE
job status updates for firefox

### ISSUE THREAD

**Issue by jacknjill02** [saucelabs/node-saucelabs#71]
updateJob(username, sessionId, status) is unable to update the status for firefox browser though it is working fine with chrome browser.

**Comment by wswebcreation** [comment]
Hi @jacknjill02

Can you please provide some more information like for example

- the setup your are using
- some logs of the Firefox execution

It's now searching for a needle in a haystack :wink:

**Comment by jacknjill02** [comment]
@wswebcreation I am using 
version: 4.10.2
name: webdriverio
platform: Windows 10
browserName: firefox
browser version : 68

**Comment by wswebcreation** [comment]
Going to close this issue because we picked it up in our chat

**Comment by christian-bromann** [comment]
@wswebcreation what was the solution to this? Anything we could have done better?
