### ISSUE TITLE
downloadJobAsset() method doesn't create video when path is not specified 

### ISSUE THREAD

**Issue by tborys** [saucelabs/node-saucelabs#72]
Current behaviour:
When calling 

`await myAccount.downloadJobAsset(
        'job_id', 'video.mp4'
    )`

the asset is not downloaded in the current working directory.

When I added directory **with the filename** 
`await myAccount.downloadJobAsset(
        'job_id', 'video.mp4', './video.mp4'
    )`

asset got created in the cwd. 
It would be great if no directory specified it defaults to cwd, otherwise use specific one.

**Comment by wswebcreation** [comment]
@christian-bromann 

There seems to some strange behaviour  in the code. The internal code for downloading the job asset needs 3 arguments, see https://github.com/saucelabs/node-saucelabs/blob/master/src/index.js#L175

The docs tell this

```
GET /v1/jobs/{id}/{assetName}
No description available.
Example:
api.downloadJobAsset(id, filename)
```

The `index.d.ts` that is generated says this

```ts
  /**
   * Get job asset
   * @method
   * @name SauceLabs#downloadJobAsset
   * @param {string} id - job id
   * @param {string} filename - filename
   */
  downloadJobAsset(id: string, filename: string): Promise<File>;
```

A quick and dirty fix like below would solve the problem for now by adding the blow code here https://github.com/saucelabs/node-saucelabs/blob/master/src/index.js#L182

```js
    if(!downloadPath){
        downloadPath = `./${assetName}`
    }
```

But the docs and `index.d.ts` are not aligned with the code.

What do you think?

**Comment by christian-bromann** [comment]
@tborys thanks for reporting the issue and @wswebcreation thanks for looking into it. I updated the docs to reflect this command a bit better. It will only store the asset to your FS if you provide a 3rd parameter because sometimes you want to work with the job asset in your script without storing it.
