### ISSUE TITLE
Platform Configurator Copy Code section scrolls erroneously for Chrome

### ISSUE THREAD

**Issue by Thor07** [saucelabs/node-saucelabs#73]
Unable to fetch values from any tab other than Java for following config.
MacOSX 
Chrome 76.0
Tried for following config:
![Screen Shot 2019-09-02 at 2 06 42 PM](https://user-images.githubusercontent.com/46732495/64086259-3d0e3400-cd8b-11e9-9add-19b351d82007.png)

caps['browserName'] = 'Safari';
caps['appiumVersion'] = '1.8.1';
caps['deviceName'] = 'iPad Pro (9.7 inch) Simulator';
caps['deviceOrientation'] = 'portrait';
caps['platformVersion'] = '11.2';
caps['platformName'] = 'iOS';

**Comment by wswebcreation** [comment]
@Thor07 

Can you please explain how this question is related to this module?

**Comment by Thor07** [comment]
@wswebcreation the node tab along with others for platform configurator on https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/ was buggy and not opening hence opened this thread. Seems fixed now.

**Comment by wswebcreation** [comment]
This module is not about the platform configurator, so thanks for closing it.
