### ISSUE TITLE
Release notes / CHANGELOG

### ISSUE THREAD

**Issue by esimons** [saucelabs/node-saucelabs#79]
Would it be possible to publish some release notes / CHANGELOG documentation for consumers to know what's changed between releases? At the very least, for major version bumps?

At present it's difficult to know what breaking change warranted the bump from v3 to v4, and I recall having similar issues with the API back when it went from v1 to v2 (see https://github.com/saucelabs/node-saucelabs/pull/61)

**Comment by christian-bromann** [comment]
@esimons definitely! For now, just check the commit history as there aren't that many commits be done.

**Comment by christian-bromann** [comment]
Yes, moving to got was to big of a risk to not choose a major version bump, especially since setting proxy via environmental variables won’t work in v4 anymore.

**Comment by christian-bromann** [comment]
Moving on we will publish release logs in the [release tab](https://github.com/saucelabs/node-saucelabs/releases).
