### ISSUE TITLE
Issue creating sauce connect tunnel for real mobile devices

### ISSUE THREAD

**Issue by sjana-aj** [saucelabs/node-saucelabs#91]
I see the issue creating sauce connect tunnel for real mobile devices. It's happening due to duplication of api key argument in sauce connect command being generated when custom api key provided to create tunnel for real device testing.

**Code Block**
```
    const sc = await myAccount.startSauceConnect({
        /**
         * you can pass in a `logger` method to print Sauce Connect log messages
         */
        logger: (stdout) => console.log(stdout),
        /**
         * see all available parameters here: https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+Command-Line+Quick+Reference+Guide
         * all parameters have to be applied camel cased instead of with hyphens, e.g.
         * to apply the `--tunnel-identifier` parameter, set:
         */
        restUrl: 'https://us1.api.testobject.com/sc/rest/v1',
        apiKey: 'XXXCustomAPIKeyProvidedXXX',
        tunnelIdentifier: 'myTunnel',
        noSslBumpDomains: '*.example.com'
    })
```

**Sauce Connect command generated**

`7 Jul 01:58:29 - Command line arguments: C:\Users\Sitam\Desktop\sauce-labs\node_modules\saucelabs\build\.sc-v4.5.4\bin\sc.exe --rest-url=https://us1.api.testobject.com/sc/rest/v1 --api-key=XXXCustomAPIKeyProvidedXXX --tunnel-identifier=myTunnel --no-ssl-bump-domains=*.example.com --user=xxx --api-key=XXXDefaultAPIKeyAddedXXX`

Please notice the duplicate `--api-key` argument above which is causing trouble here.

**Comment by enriquegh** [comment]
@sjana-aj 
`apiKey` is not a valid parameter at the moment.

You will need to set the username and access key when instantiating the SauceLabs object.

So you can do:

```node
import SauceLabs from 'saucelabs';

(async () => {
    const myAccount = new SauceLabs({user: 'username', key: 'rdc_api_key'});
    const sc = await myAccount.startSauceConnect({
        logger: (stdout) => console.log(stdout),
        restUrl: 'https://us1.api.testobject.com/sc/rest/v1',
        tunnelIdentifier: 'myTunnel',
        noSslBumpDomains: '*.example.com'
    })
    await sc.close()

})()
```
Since the access key used for RDC Sauce Connect and other services is different you might end up needing two separate instances to SauceLabs but that'll depend on exactly what you're trying to accomplish.

**Comment by sjana-aj** [comment]
thanks @enriquegh , this helped! I see sauce connect for real devices is working using this approach. thanks again (y)
