### ISSUE TITLE
Pull always latest Sauce Connect version if not specified otherwise

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/node-saucelabs#93]
We should update the `sc` command to always pull the latest Sauce Connect version from https://saucelabs.com/versions.json.

**Comment by christian-bromann** [comment]
Let's hold off for a second as it seems that fetching that endpoint takes quite some time:
```sh
curl https://saucelabs.com/versions.json  0.02s user 0.01s system 0% cpu 22.058 total
```
Checking back with the team.

**Comment by joventuraz** [comment]
> Let's hold off for a second as it seems that fetching that endpoint takes quite some time:
> 
> ```shell
> curl https://saucelabs.com/versions.json  0.02s user 0.01s system 0% cpu 22.058 total
> ```
> 
> Checking back with the team.

This seems to be fixed? I'm getting a very fast response... another way would be to scrape it from https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy but that is dirty IMO

**Comment by christian-bromann** [comment]
@joventuraz could have been a temporary issue with the S3 bucket, so happy to move forward with maintaining a hardcoded fall back.
